- algoliasearch/algoliasearch.py
This commit allows to use the python client to connect to algolia behind a proxy.
This uses the "http_proxy" env variable.
> Connect to algolia behind a proxy

- .travis.yml
- tox.ini
The problem was due to the fact that travis does not yet have python 3.5 in its prebuilt image.
More here https://github.com/travis-ci/travis-ci/issues/4794
> Allow tox to run the py35 profile

- algoliasearch/__init__.py
Until now `algoliasearch.version.VERSION` was needed to obtain the current version. Only `algoliasearch.VERSION` is now needed.
The change is backward compatible: it is still possible to do `algoliasearch.version.VERSION`.
> Make VERSION easier to access

- algoliasearch/client.py
- algoliasearch/index.py
- algoliasearch/transport.py
- setup.py
- tests/test_index.py
additionally fix default client timeouts and resources path
> Refactor Transport out of Client

- algoliasearch/index.py
- tests/test_client.py
- tests/test_index.py
getObjects did not expose the attributesToRetrieve parameter, as noticed in [algoliasearch-client-android's #129](https://github.com/algolia/algoliasearch-client-android/issues/129).
Fixed in this PR by adding a default parameter and an unit-test.
> Index: implement get_objects with attributes_to_retrieve

- algoliasearch/helpers.py
- tests/test_index.py
Use `calendar.timegm` and `datetime.utctimetuple` to handle non-local datetime timestamp conversion correctly.
References:
https://docs.python.org/3/library/time.html#time.mktime
https://docs.python.org/3/library/calendar.html#calendar.timegm
> Fix datetime timestamp conversion when datetime is not in local time

- algoliasearch/client.py
- tests/test_client.py
This endpoint does an application-level ping. It is only useful for diagnosis purposes, or to pre-establish a connection before running actual operations.
> feat: Add support for the `/1/isalive` endpoint

- .travis.yml
- tests/test_index.py
- tox.ini
Those versions are not compatible anymore with some of our
dependencies, which causes the tests to fail no matter what.
> ci: remove automatic testing of py26 and py32

- algoliasearch/index.py
- Parameters must be posted inside the body, not put in the URL.
- Absent parameters must be omitted; the empty string is not a valid value (except for the query string). The anchoring, for example, only accepts `contains`, `is`, `endsWith` and `startsWith`.
> fix: Fix rule search (`Index.search_rules`)

- algoliasearch/client.py
- algoliasearch/index.py
- algoliasearch/transport.py
Fixes the [algoliasearch-async issue](https://github.com/algolia/algoliasearch-client-python/pull/301#issuecomment-341087416) reported by @talaus-signifai.
> fix(Client/Index/Transport): Make request_options optional

- algoliasearch/index.py
- tests/__init__.py
- tests/conftest.py
- tests/helpers.py
- tests/test_client.py
- tests/test_compat.py
- tests/test_index.py
- tests/test_keys.py
Implement an easy way to iterate over synonyms of an index.
> feat: iter_synonyms

- algoliasearch/index.py
> Index::get_objects: Accept only list for attributes_to_retrieve

- algoliasearch/index.py
- tests/test_index.py
Follow up of https://github.com/algolia/algoliasearch-client-go/issues/397.
> fix: Prevent saving a rule with an empty objectID

- algoliasearch/client.py
- algoliasearch/index.py
Same as https://github.com/algolia/algoliasearch-client-php/pull/378
All keys should be managed using the Client class.
If you use the Index class, you'll attached the key to the index internally. They are not displayed in the dashboard and cannot be retrieve with `client::list_api_keys`. This is a deprecated feature, that shouldn't be used anymore.
Instead, you can create a key using `client::add_api_key` that will be attached to the Application internally. **You can add restriction on the index to achieve the same behavior**.
Other methods like get, update, delete, list are still required to access your existing keys.
In the same PR, I fixed #359
> Deprecate key management via the index class

- algoliasearch/index.py
- tests/test_index.py
Cursor can get very long and exceed the max url size, for that reason we always pass it in the body of the request.
In case params is empty, we need to fallback on GET, because Algolia's API doesn't allow POST request with an empty body.
> Browse: Ensure cursor is passed in the body

- algoliasearch/index.py
`Index::delete_object` needs a non-empty objectID
If the object_id is empty, the entire index will be deleted instead of one record.
> Fix deleteObject needs a valid object_id

- CHANGELOG.md
- algoliasearch/index.py
- tests/helpers.py
- tests/test_index.py
Adds methods `replace_all_rules` and `replace_all_synonims`.
> Adds replace_all_rules and replace_all_synonyms

- CHANGELOG.md
- algoliasearch/client.py
- tests/test_client.py
We decided to expose more methods like `multiple_queries` to the client.
* `multiple_get_objects` allows you to get objects by objectID from multiple indices
* `multiple_batch_objects` allows you to add, update or delete objects from multiple indices. (note: the `batch` method already existed in the python client but we added this one for consistency with other cleints)
Related conversations:
* https://github.com/algolia/algoliasearch-client-php/pull/295
* https://github.com/algolia/algoliasearch-client-javascript/issues/710
> feat: add multiple objects endpoint methods

- CHANGELOG.md
- algoliasearch/index.py
- tests/test_index.py
Bug: If you try to call `replace_all_objects` with a set of objects without a valid `objectID` the library will raise this error: 
```python
KeyError: 'objectID'
```
The solution is the usage of the method `addObjects` instead of the `saveObjects`, because this last one requires a valid `objectID`.
> Fixes issue while using replace_all_objects without a valid `objectID`

- README.md
| Related Issue     | 
Single and double quotes were mixed freely in the Python code blocks. There were more double than single, so went with double throughout.
Nothing functional, just conveys a cleaner, more readable code base to other devs.
> make double quotes usage consistent in Python code

- CHANGELOG.md
- algoliasearch/search_index.py
The `batch ` algorithm was broken as it was sending to Algolia the list of objects instead of the batch it self.
> Fixes chunk algorithm on batch size limit

- requirements.txt
- setup.cfg
| Related Issue     | Fix #422  
I've changed the typing requirement to only be installed if the python version is less than 3.5. This is because `typing` is included in the standard library for 3.5 and above. You can read more here https://docs.python.org/3/library/typing.html and in issue #422 
The issue described in #422
> Fix conflict with standard library for typing dependency

- algoliasearch/search_index.py
- tests/unit/test_search_index.py
| Related Issue     | n/a
Pop `attributesToRetrieve` from `request_options` before iterating over object_ids in order to ensure that:
1) it's applied to each request created by the function
2) it's not present in the main request parameters
Without this or a similar change, `attributesToRetrieve` is only applied to the first object, all other objects are retrieved with all attributes
> Apply attributesToRetrieve parameter to each request created by index.get_objects

- CHANGELOG.md
- algoliasearch/search_index.py
- algoliasearch/search_index_async.py
- tests/features/test_account_client.py
- tests/unit/test_search_index.py
| New feature?      |no    
| Related Issue     | [#425](https://github.com/algolia/algoliasearch-client-python/issues/425)
There is a bug, getVersion=2 is meant to be set as a URL parameter and not a header.
With AccountClient we duplicate synonyms because getSettings without `getVersion=2` use as default `getVersion=1` and in the version 1 synonyms were consider as settings. 
- Improve test suite with a robust test
- fix bug 
- correct getSettings method (sync/async)
> Fix get_settings 

- tests/features/test_search_index.py
| Related Issue     | Fix https://github.com/algolia/algoliasearch-client-python/issues/441
Implement the new indexLanguages setting which is an array of strings.
Currently, only ["ja"] is supported by the engine.
> added(settings): indexLanguages parameter

- tests/features/test_search_index.py
| Related Issue     | Fix #442 
Adds the new `Alternatives` field in the concerned test.
Fix #442
> internal: update query rule test with alternative

- algoliasearch/search_index.py
- algoliasearch/search_index_async.py
- tests/features/test_search_index.py
- tests/unit/test_search_index.py
Added a method to check if index exists
| Related Issue     | Fix https://github.com/algolia/algoliasearch-client-python/issues/434
Add a method to check if the index exists
> feat: adds index exists

- algoliasearch/exceptions.py
This pull request makes all exceptions extend the default Algolia one.
> fix: makes unreachable be an algolia exception

- algoliasearch/exceptions.py
- algoliasearch/helpers.py
- algoliasearch/http/request_options.py
- algoliasearch/search_index.py
- algoliasearch/search_index_async.py
- tests/features/test_search_index.py
- tests/unit/test_search_index.py
Close #439 
- [Specs and CTS tests](https://github.com/algolia/algoliasearch-client-specs-internal/pull/41)
- [Go client base implementation](https://github.com/algolia/algoliasearch-client-go/pull/524)
@nunomaduro Your review can wait until you come back from vacations (please!).
@nunomaduro @clemfromspace As I replied to Nuno in one of my comments, I'd really like to know if it's possible and how to avoid all the copy/pasting between the sync and async versions of the `search_index.find_first_object` function.
> feat: unit test relevance

- algoliasearch/search_index.py
- algoliasearch/search_index_async.py
- tests/unit/test_search_index.py
| Related Issue     | Fix #453 
Adds missing request_options into `exists` method.
> fix: adds request_options into exists method

- algoliasearch/exceptions.py
- algoliasearch/search_client.py
- tests/features/test_search_client.py
- tests/unit/test_search_index.py
This pull request adds `get_secured_api_key_remaining_validity ` as specified on the api client specs.
closes #443
> feat(remaining-validity): adds get_secured_api_key_remaining_validity

- README.md
`save_objects` expects a list of (`dict`) objects.
| Related Issue     | Fix #...  
Fix syntax error in README code example.
`save_objects` expects a list of (`dict`) objects.
> Update syntax error in README

- tests/features/test_search_index.py
- tests/helpers/misc.py
**Summary**
Set `userData` in the Settings test in the CTS. Because the Settings test was not fully implemented, this commit also implements the test with all the missing fields.
> test: add userData to test_settings for CTS test

- algoliasearch/search_index.py
- tests/features/test_search_index.py
- tests/unit/test_search_index.py
This pull request fixes the fact that the replace all objects could get blocked on the replace all objects method while using `safe` parameter with async dependencies.
> fix(safe-replace-all-objects): blocking operation on save temporary objects

- CHANGELOG.md
- algoliasearch/search_index_async.py
| Related Issue     | fixes #481
Just like https://github.com/algolia/algoliasearch-client-python/pull/479 ensured we have a safe and new client for the replace all objects in sync mode. This pull request ensures the same thing for the async mode.
> fix(blocked-replace-all-objects): do not share same client

- setup.cfg
| Related Issue     | #499 
This pull request fixes the invalid format used on the `setup.cfg` -> `python_requires` line.
> fix(setup-cfg): invalid format in python requires

- algoliasearch/http/request_options.py
Needed for doc snippets here: https://github.com/algolia/doc/pull/4737
> fix: accept X-Algolia-UserToken as a valid extra header for RequestOptions

- DOCKER_README.md
- Dockerfile
- README.md
- requirements.txt
- tox.ini
| Related Issue     | Fixes https://github.com/algolia/algoliasearch-client-python/issues/517
Add a Dockerfile and a guide to setup Docker for the repository
Ease contributions to the Python client
- Follow [README](https://github.com/algolia/algoliasearch-client-python/blob/1bac766fd921910a3423afed77fc77b456ba77bd/DOCKER_README.md) steps
- In image's bash run 
- `tox -e format` to run linter check
- `tox -e types` to run type check
- `tox -e py38-sync,py38-async` to run tests for Python 3.8
> chore(docker): containerize repo

- algoliasearch/iterators.py
- algoliasearch/iterators_async.py
- tests/features/test_search_index.py
| Related Issue     | Support ticket
`if self._raw_response["nbHits"] < self._data["hitsPerPage"]:` was never validated since `nbHits` does not represent the number of returned hits but the total of hits.
We now compute `nbHits` on the `len(hits)`.
Recursion was never ending with iterations > 1000 `hitsPerPage`. 
I've set an index (`python_repro_rules`) with 3k+ rules on this app (`QPBQ67WNIG`)
```py
from algoliasearch.search_client import SearchClient, SearchConfig
config = SearchConfig('QPBQ67WNIG', 'SEARCH_API_KEY')
client = SearchClient.create_with_config(config)
index = client.init_index('python_repro_rules')
i = 0
for rule in …
```
> fix(iterators): prevent recursion issue

- algoliasearch/http/requester.py
- algoliasearch/iterators.py
- algoliasearch/iterators_async.py
- tests/unit/test_helpers.py
- tests/unit/test_search_index.py
- tox.ini
We now encode the path using the `endpoint` method (like we do in the Client transporter calls).
Path parameters in the `iterators` were not encoded.
> fix(iterators): encode path parameters

- algoliasearch/iterators.py
- algoliasearch/iterators_async.py
- tox.ini
| Related Issue     | fixes https://github.com/algolia/algoliasearch-client-python/pull/550 fixes https://github.com/algolia/algoliasearch-client-python/issues/544
https://algolia.atlassian.net/browse/CR-2497
https://algolia.atlassian.net/browse/DI-676
We ensure the key in present before calling pop, to prevent a KeyError returned if it's not found.
> fix: prevent KeyError when popping an unknown property

- .circleci/config.yml
- CHANGELOG.md
- README.md
- algoliasearch/analytics_client_async.py
- algoliasearch/helpers_async.py
- algoliasearch/http/requester_async.py
- algoliasearch/http/transporter_async.py
- algoliasearch/insights_client_async.py
- algoliasearch/iterators_async.py
- algoliasearch/personalization_client_async.py
- algoliasearch/recommend_client_async.py
- algoliasearch/recommendation_client_async.py
- algoliasearch/search_client_async.py
- algoliasearch/search_index_async.py
- algoliasearch/version.py
- setup.cfg
- tests/helpers/misc_async.py
- tox.ini
| Related Issue     | Fix #549, Fix #551
This PR removes support for python 2.7, adds support for python 3.11 and tests the project against 3.9, 3.10, and 3.11:
- Replaced all @asyncio.coroutine decorators by async def function def
- Replaced `yield from` with `await` or `return` statements
- Added python 3.9, 3.10, and 3.11 to tox and circleci
Due to a removed syntax in python 3.11, the package was not working.
> feat: add support for Python 3.9, 3.10 and 3.11
