algoliasearch/algoliasearch.py
tests/test_client.py

refs #18 
@Jerskouille what do you think?

Fix browse_from and browse_all

---

README.md

I forgot to update the README.md after my most recent changes for the GAE update (now merged in 1.7.1), so here's a fix.

Update README.md for consistency with GAE update

---

ChangeLog

Bump to 1.9.0

---

algoliasearch/index.py

This is a purely internal change.

Invert the use of forward_to_{slaves,replicas}

---

.travis.yml

Put credential directly on the travis website

tests: fix CI

---

algoliasearch/index.py

Makes it easier to work with multiple indexes from the repl.

Add repr methods

---

algoliasearch/index.py

Small helper to easily export all the synonyms or all the rules in an index.
**Note:** Depends on #296.

feat: Iterators on synonyms and rules of an index

---

algoliasearch/client.py

I didn't run tests or install it, should any test change?

fix(list_user_ids): actually forward page and hitsPerPage

---

.travis.yml
tests/conftest.py
tests/helpers.py
tests/test_MCM.py
tests/test_compat.py
tests/test_index.py
tests/test_keys.py
tox.ini

I'm open to any other way of doing it.

Build community PRs

---

algoliasearch/client.py

We're adding the language version to each client. Please let me know what yout think, any comment is welcome.
Django PR is coming.

Add python version to the UserAgent

---

CHANGELOG.md
algoliasearch/index.py
tests/test_index.py

Adds method `replace_all_objects`.

Adds replace_all_objects

---

CHANGELOG.md
algoliasearch/client.py
tests/test_client.py

This Pull Request adds `copy_settings`, `copy_synonyms` and `copy_rules`.

Adds copy settings, copy synonyms and copy rules

---

CHANGELOG.md
algoliasearch/client.py
tests/test_client.py

This Pull Request adds `Perso`.

[1.19] Adds personalization

---

CHANGELOG.md
algoliasearch/__init__.py
algoliasearch/client.py
algoliasearch/insights_client.py
algoliasearch/user_insights_client.py
tests/conftest.py
tests/test_insights_client.py
tests/test_user_insights_client.py

This Pull Request adds `Insights Client`.

[1.19] Adds Insights Client

---

CHANGELOG.md
algoliasearch/insights_client.py
algoliasearch/user_insights_client.py
tests/test_insights_client.py
tests/test_user_insights_client.py

Returns raw `response` from insights methods.

[1.19.1] Returns response from insights related methods

---

tests/features/test_search_index.py

This pull request updates the cts concerning contextual rules.
closes #451

feat(contextual rules): adds tests

---

.travis.yml
tests/features/http/test_requester.py
tests/features/test_account_client.py
tests/features/test_analytics_client.py
tests/features/test_insights_client.py
tests/features/test_search_client.py
tests/features/test_search_index.py
tests/helpers/factory.py
tests/helpers/misc.py
tests/unit/test_account_client.py

This pull request applies the changes about the CTS concerting solving flakiness. Addresses https://github.com/algolia/algoliasearch-client-specs-internal/pull/105

chore: fixes tests flakyness

---

algoliasearch/search_client.py
tests/features/test_search_client.py

| Related Issue     | Fix #460

Feat: has_pending_mappings

---

algoliasearch/configs.py
algoliasearch/recommendation_client.py
algoliasearch/recommendation_client_async.py
algoliasearch/search_client.py
tests/features/test_recommendation_client.py
tests/helpers/factory.py

This pull request adds personalisation methods.
fixes https://github.com/algolia/algoliasearch-client-python/issues/461
fixes #472

feat(recommendation-client): adds personalization methods

---

algoliasearch/search_client.py
tests/features/test_search_client.py

feat(assign-user-ids): adds method and tests

---

CHANGELOG.md
algoliasearch/analytics_client.py
algoliasearch/analytics_client_async.py
algoliasearch/http/requester.py
algoliasearch/http/requester_async.py
algoliasearch/http/transporter.py
algoliasearch/http/transporter_async.py
algoliasearch/insights_client.py
algoliasearch/insights_client_async.py
algoliasearch/iterators_async.py
algoliasearch/recommendation_client.py
algoliasearch/recommendation_client_async.py
algoliasearch/search_client.py
algoliasearch/search_client_async.py
algoliasearch/search_index_async.py
tests/features/test_account_client.py
tests/features/test_analytics_client.py
tests/features/test_insights_client.py
tests/features/test_recommendation_client.py
tests/features/test_search_client.py
tests/features/test_search_index.py
tests/helpers/misc_async.py

| Related Issue     | fixes https://github.com/algolia/algoliasearch-client-python/issues/419
This pull request adds the possibility of the developer to `close` open http sessions. It also fixes the warning detailed on the issue https://github.com/algolia/algoliasearch-client-python/issues/419.

feat: closeable clients

---

MAINTAINERS.md

This pull request updates the code owners of this repository.

chore(maintainers): updates code owners

---

tests/features/test_account_client.py
tests/features/test_search_client.py
tests/features/test_search_index.py
tests/helpers/misc.py
tests/unit/test_search_client.py

This pull request up-to-dates the CTS concerning:
- The issue on the metadata on rules
- Removes leftover about the recommendation test
- Removes flaky DSN test

chore(cts-maintenance): applies fixes concerning metadata, dns, and others

---

tests/features/test_search_index.py

| Related Issue     | Fix #496
This pull request updates the cts concerning multiple condition rules.

tests(rules-multiple-conditions): updates cts

---

.circleci/config.yml
tox.ini

| Related Issue     | 
Revert unwanted changes during the release

chore(tooling): revert unwanted changes
